name: Test workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make test executable
        run: chmod +x test.sh
      - name: Build
        run: g++ -std=c++17 *.cpp
      - name: Run test
        run: ./test.sh
      - name: diff
        run: diff output.txt good_output.txt
