
name: Test workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: g++ -std=c++17 *.cpp
      - name: Permission
        run: chmod u+r+x test.sh
      - name: Run test
        run: ./test.sh
      - name: Install tools
        run: sudo apt-get install -y valgrind cppcheck
      - name: Gplusplus Wall
        run: g++ -Wall -Werror *.cpp
      - name: Valgrind
        run: valgrind --error-exitcode=1 ./a.out units/Maple.json units/Sally.json
      - name: Cppchecks
        run: cppcheck *.cpp --enable=warning --error-exitcode=1
      - name: Cppcheck report
        run: cppcheck *.cpp --enable=warning --output-file=report.txt
      - name: Artifacting
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./report.txt
      - name: Diffy
        run: diff --strip-trailing-cr output.txt exp_output.txt
